### ISSUE TITLE
LIPIcs-21 cannot open file for embedding sRGB on Windows 10 and MikTex 

### ISSUE THREAD

**Issue by piskachev** [dagstuhl-publishing/styles#10]
With the new version of LIPIcs, I get the following error when I try to compile the provided example in the template. 

pdfTeX error (ext5): cannot open file for embedding. ...e\pdfobj stream attr{/N 3} file{sRGB.icc}

Any ideas what the issue is and how to solve are welcome.

**Comment by java7mike** [comment]
Sorry for the inconveniences. We will immediately prepare a revised, more robust version of the style.

For the meantime, it might be sufficient to manually download the file sRBG.icc from https://ctan.org/tex-archive/support/colorprofiles and to add it to your source folder.

**Comment by java7mike** [comment]
The new version should resolve the issue. It would be great if you could test this also on your machine.

**Comment by piskachev** [comment]
Thanks for the quick action!. It works well now.
