### ISSUE TITLE
mktexpk does not generate font fa5free0solid

### ISSUE THREAD

**Issue by glipari** [dagstuhl-publishing/styles#13]
Hello,

I am trying the compile the sample file for authors on my Ubuntu 18.04 distribution, I use TeXlive 2017. 
It give me the following error: 

----

kpathsea: Running mktexpk --mfmode / --bdpi 600 --mag 0+540/600 --dpi 540 fa5free0solid
mktexpk: don't know how to create bitmap font for fa5free0solid.
mktexpk: perhaps fa5free0solid is missing from the map file.
kpathsea: Appending font creation commands to missfont.log.

!pdfTeX error: pdflatex (file fa5free0solid): Font fa5free0solid at 540 not fou
nd
 ==> Fatal error occurred, no output PDF file produced!

--- 

Can you please help me ?

**Comment by krono** [comment]
You need the [fontawesome](https://www.ctan.org/pkg/fontawesome) package installed.

**Comment by glipari** [comment]
Thanks. I finally took the step of updating my TeXlive and it works.
