### ISSUE TITLE
Text in definition and exercise should not be in italic

### ISSUE THREAD

**Issue by L-TChen** [dagstuhl-publishing/styles#18]
It is unconventional and rather pointless to put the text of a definition (and exercise) in italic. That's also why the theorem style recommended for definitions by `amsthm` is called `definition`.

**Comment by java7mike** [comment]
This is especially mentioned and explained in the LIPIcs author guidelines:

> In difference to the style provided by amsthm package, the body of the definition
environment is formatted as in theorem environments, e. g. italic text and not upright text
as in the original environment. This should help to separate text of the definition from
surrounding regular text. If an upright text as in the original environment is preferred, please
add an alternative definition environment to the document preamble, e. g. as follows:
\theoremstyle{definition}
\newtheorem{definition2}[theorem]{Definition}

**Comment by L-TChen** [comment]
If this is a matter of choice and allowed to change, then it will be helpful at least to have an option to change the style easily.

**Comment by L-TChen** [comment]
Defining a new environment is rather troublesome if the manuscript is initially written in another style with `definition` used. It is possible to redefine the environment `definition` with a few more commands but it requires some effort. Please don't put extra effort unnecessarily on authors. Thanks.
