### ISSUE TITLE
With the 2023 version of TexLive, there is a comma at the top-left corner of the last page. Always.

### ISSUE THREAD

**Issue by deividrvale** [dagstuhl-publishing/styles#31]
The problem, with the following version of texlive (or later)
```bash
pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023)
```
a comma always appears in the last paper of the any documents using lipics style v2019 class
whenever the option for pdfa is given as argument.
The comma appears as in the image below.

<img width="191" alt="Screenshot 2023-06-08 at 13 38 47" src="https://github.com/dagstuhl-publishing/styles/assets/5068803/5c81684b-9dd4-433a-8bb4-a36baf225b0d">

I could reproduce this in two macOS computers, Linux and Windows all with TeX Live 2023.
TeX Live 2022 doesn't have the issue.

Searching for possible solutions I came across with the following:

[https://tex.stackexchange.com/questions/365600/spurious-comma-appears-when-combining-hyperref-pdfa-with-hyperxmp](https://tex.stackexchange.com/questions/365600/spurious-comma-appears-when-combining-hyperref-pdfa-with-hyperxmp
)

but I was not able to fix it in the lipics class myself. So I'm reporting the problem here.

Note: this might impact more people, since for instance arixv is updating their texlive version to 2023 as well.

Thank you for the support, and I hope that this helps to fix the bug.

**Comment by java7mike** [comment]
This issue has already been resolved with the minor updated version released four weeks ago. 
https://github.com/dagstuhl-publishing/styles/releases/tag/v2021.1.3
