### ISSUE TITLE
\qedhere in claimproof yields wrong qed symbol

### ISSUE THREAD

**Issue by sebschmi** [dagstuhl-publishing/styles#4]
The following lets the claimproof end with a filled triangle, instead of an empty one. On the other hand, removing `\qedhere` makes the correct qed symbol appear, but on a new line after the enumerate.

Example:
```latex
\begin{claim}
    abc abc abc
\end{claim}
\begin{claimproof} abc abc abc
    \begin{enumerate}
        \item abc abc abc \qedhere{}
    \end{enumerate}
\end{claimproof}
```

**Comment by java7mike** [comment]
Adding `\renewcommand\qedsymbol{\textcolor{lipicsGray}{\ensuremath{\vartriangleleft}}}` after `\begin{claimproof}` should solve the problem at least for simple scenarios like the one in your example.

However this would not resolve the problem in case of more complex scenarios, e.g. in case of a regular proof within the claimproof. Maybe we should provide a `\claimqedhere`
