### ISSUE TITLE
lipics-v2019 template outdated on overleaf

### ISSUE THREAD

**Issue by Pr0gm4n** [dagstuhl-publishing/styles#8]
Hello,

I realized (by trying to use the option 'anonymous') that the template you have published on overleaf.com is outdated. After contacting the Overleaf support, I received this response:

> [...] This template was contributed to our Overleaf gallery by the publisher. It looks like the anonymous option was added to their template in a newer update than they've published on Overleaf. The newest code I found is available here: https://submission.dagstuhl.de/documentation/authors#lipics 
> 
> If the publisher would like to keep the Overleaf template current, they can update it following the steps here: https://www.overleaf.com/learn/how-to/How_do_I_update_a_template,_example_or_article_I%27ve_published_in_the_Overleaf_gallery%3F I'd suggest contacting the publisher about this directly, because this template is not managed by Overleaf staff.

I kindly suggest to follow their steps to keep the template updated. Thank you very much!

Best regards,
Roland

**Comment by java7mike** [comment]
Dear Roland,

thanks for your suggestion. We have just updated the LIPIcs (and also OASIcs) template on overleaf, see

https://www.overleaf.com/latex/templates/lipics-v2019-sample/gqgybwgdpbpq
https://www.overleaf.com/latex/templates/oasics-v2019-sample/mmkzztggvmxw

Best regards,
Michael
