### ISSUE TITLE
lipics: Related version not hidden in anonymous mode

### ISSUE THREAD

**Issue by ni-tro** [dagstuhl-publishing/styles#9]
I noticed that the anonymization feature does not hide the \relatedversion-field. According to [this study](https://arxiv.org/abs/2007.00177), this can have the effect that "less confident reviewers are more likely to assign high review scores to papers with well known authors and low review scores to papers with less known authors".

I suppose the lipics package should encourage hiding the \relatedversion-field.

**Comment by java7mike** [comment]
Yes, I agree that the \relatedversion field should also be hidden. The same is true for the \supplement field. We will implement this in the next revision.
